-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

-- Pywal Dynamic Colors Integration
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.cache/wal/?.lua"
local colors = require("colors-hyprland")

--###############
--## MONITORS ###
--###############
require("monitors")

hl.monitor({
    output      = "eDP-1",
    bitdepth    = 10,
    cm         = "srgb",
    sdr_eotf    = "gamma22"
})

hl.config({
    render = {
        cm_enabled  = true,
        cm_sdr_eotf = "gamma22"
    }
})
--############################
--## ENVIRONMENT VARIABLES ###
--############################

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

--####################
--## LOOK AND FEEL ###
--####################

hl.config({
    general = {
        ["col.active_border"] = colors.color1,
        ["col.inactive_border"] = colors.color0,
        gaps_in = 5,
        gaps_out = 10,
        border_size = 1,
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },
})

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 5,
        active_opacity = 1.0,
        inactive_opacity = 0.7,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = colors.color0,
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})
hl.layer_rule({
    name      = "eww-panel-animation",
    match     = {
        namespace = "eww-panel"
    },
    animation = "slide right", -- Options: popin, fade, slide [top/bottom/left/right]
})
hl.layer_rule({
    name = "rofi-animation",
    match = {
        namespace = "rofi"
    },
    animation = "slide bottom",
})
hl.animation({
    leaf    = "global",
    enabled = true,
    speed   = 5,
    bezier  = "default"
})
hl.animation({
    leaf    = "layers",
    enabled = true,
    speed   = 4,
    bezier  = "default"
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
})

--############
--## INPUT ###
--############

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################
--## KEYBINDINGS ###
--##################

local mainMod = "SUPER"

-- Core Applications & Window Operations
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("alacritty"))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + V", hl.dsp.window.float())
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("eww open --toggle control_panel"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("rofi -i -show drun"))

-- Move Focus (Arrows)
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch Workspaces
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move Active Window to Workspaces
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Special Workspace (Scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Workspace Navigation via Mouse Scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mouse Window Resizing & Dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- Media Control Bindings (Volume & Brightness with 1.5s Auto-Dismiss) ---

-- Volume Control (wpctl)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd([[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify-send -e -t 1500 -h string:x-canonical-private-synchronous:volume_notif -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')" -i "audio-volume-high" "Volume" "Increasing volume..." -a "System"]]), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd([[wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -e -t 1500 -h string:x-canonical-private-synchronous:volume_notif -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')" -i "audio-volume-low" "Volume" "Decreasing volume..." -a "System"]]), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd([[wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && [ "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o 'MUTED')" = "MUTED" ] && notify-send -e -t 1500 -h string:x-canonical-private-synchronous:volume_notif -i "audio-volume-muted" "Muted" "Audio output silenced" -a "System" || notify-send -e -t 1500 -h string:x-canonical-private-synchronous:volume_notif -i "audio-volume-high" "Unmuted" "Audio output active" -a "System"]]), { locked = true })

-- Display Brightness Control (brightnessctl)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd([[brightnessctl set 5%+ && notify-send -e -t 1500 -h string:x-canonical-private-synchronous:brightness_notif -h int:value:"$(brightnessctl -m | awk -F, '{print substr($4, 1, length($4)-1)}')" -i "display-brightness" "Brightness" "Increasing brightness..." -a "System"]]), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd([[brightnessctl set 5%- && notify-send -e -t 1500 -h string:x-canonical-private-synchronous:brightness_notif -h int:value:"$(brightnessctl -m | awk -F, '{print substr($4, 1, length($4)-1)}')" -i "display-brightness" "Brightness" "Decreasing brightness..." -a "System"]]), { repeating = true })

-- Media Playback
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("hyprshot -m output"))

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

--#################
--## AUTOSTART ####
--#################

hl.on("hyprland.start", function()
    hl.exec_cmd("killall -9 eww && eww daemon &")
    hl.exec_cmd("waybar & awww-daemon & swaync &")
    hl.exec_cmd("nm-applet &")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("nmcli device disconnect wlan0; nmcli device connect wlan0")
    hl.exec_cmd("blueman-applet")
end)
