-- Generated by nwg-displays on 2026-08-14 at 15:50:24. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.0",
    position = "0x0",
    scale = 1,
    bitdepth = 10
})
