-- Generated by nwg-displays on 2026-07-28 at 17:27:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.0",
    position = "0x0",
    scale = 1.0,
    mirror = "10",
    bitdepth = 10
})
